### ISSUE TITLE
Fails to compile on macOS 14.2.1 ARM64

### ISSUE THREAD

**Issue by XVilka** [ublk-org/qcow2-rs#1]
```
error[E0425]: cannot find value `MAP_POPULATE` in crate `libc`
    --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/util.rs:19:42
     |
19   |                 libc::MAP_SHARED | libc::MAP_POPULATE,
     |                                          ^^^^^^^^^^^^ help: a constant with a similar name exists: `MAP_PRIVATE`
     |
    ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/apple/mod.rs:3314:1
     |
3314 | pub const MAP_PRIVATE: ::c_int = 0x0002;
     | ------------------------------ similarly named constant `MAP_PRIVATE` defined here

error[E0425]: cannot find value `MADV_DONTFORK` in crate `libc`
    --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/util.rs:35:74
     |
35   |         match unsafe { libc::madvise(self.addr.as_ptr(), self.len, libc::MADV_DONTFORK) } {
     |                                                                          ^^^^^^^^^^^^^ help: a constant with a similar name exists: `MADV_DONTNEED`
     |
    ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/apple/mod.rs:3786:1
     |
3786 | pub const MADV_DONTNEED: ::c_int = 4;
     | -------------------------------- similarly named constant `MADV_DONTNEED` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:132:25
    |
132 |         offset64: libc::off64_t = 0,
    |                         ^^^^^^^ help: a type alias with a similar name exists: `off_t`
    |
   ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
    |
1   | pub type off_t = i64;
    | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:165:39
    |
165 |         self.offset64(offset as libc::off64_t)
    |                                       ^^^^^^^ help: a type alias with a similar name exists: `off_t`
    |
   ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
    |
1   | pub type off_t = i64;
    | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:178:25
    |
178 |         offset64: libc::off64_t = 0,
    |                         ^^^^^^^ help: a type alias with a similar name exists: `off_t`
    |
   ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
    |
1   | pub type off_t = i64;
    | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:208:39
    |
208 |         self.offset64(offset as libc::off64_t)
    |                                       ^^^^^^^ help: a type alias with a similar name exists: `off_t`
    |
   ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
    |
1   | pub type off_t = i64;
    | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:258:25
    |
258 |         offset64: libc::off64_t = 0,
    |                         ^^^^^^^ help: a type alias with a similar name exists: `off_t`
    |
   ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
    |
1   | pub type off_t = i64;
    | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:291:39
    |
291 |         self.offset64(offset as libc::off64_t)
    |                                       ^^^^^^^ help: a type alias with a similar name exists: `off_t`
    |
   ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
    |
1   | pub type off_t = i64;
    | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:310:25
    |
310 |         offset64: libc::off64_t = 0,
    |                         ^^^^^^^ help: a type alias with a similar name exists: `off_t`
    |
   ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
    |
1   | pub type off_t = i64;
    | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:342:39
    |
342 |         self.offset64(offset as libc::off64_t)
    |                                       ^^^^^^^ help: a type alias with a similar name exists: `off_t`
    |
   ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
    |
1   | pub type off_t = i64;
    | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:427:23
    |
427 |         offset: libc::off64_t = 0,
    |                       ^^^^^^^ help: a type alias with a similar name exists: `off_t`
    |
   ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
    |
1   | pub type off_t = i64;
    | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:762:25
    |
762 |         offset64: libc::off64_t = 0,
    |                         ^^^^^^^ help: a type alias with a similar name exists: `off_t`
    |
   ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
    |
1   | pub type off_t = i64;
    | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:785:39
    |
785 |         self.offset64(offset as libc::off64_t)
    |                                       ^^^^^^^ help: a type alias with a similar name exists: `off_t`
    |
   ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
    |
1   | pub type off_t = i64;
    | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:793:22
    |
793 |         len: { libc::off64_t },
    |                      ^^^^^^^ help: a type alias with a similar name exists: `off_t`
    |
   ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
    |
1   | pub type off_t = i64;
    | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:795:25
    |
795 |         offset64: libc::off64_t = 0,
    |                         ^^^^^^^ help: a type alias with a similar name exists: `off_t`
    |
   ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
    |
1   | pub type off_t = i64;
    | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:817:39
    |
817 |         self.offset64(offset as libc::off64_t)
    |                                       ^^^^^^^ help: a type alias with a similar name exists: `off_t`
    |
   ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
    |
1   | pub type off_t = i64;
    | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:954:25
    |
954 |         offset64: libc::off64_t = 0,
    |                         ^^^^^^^ help: a type alias with a similar name exists: `off_t`
    |
   ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
    |
1   | pub type off_t = i64;
    | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:986:39
    |
986 |         self.offset64(offset as libc::off64_t)
    |                                       ^^^^^^^ help: a type alias with a similar name exists: `off_t`
    |
   ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
    |
1   | pub type off_t = i64;
    | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
    --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:1011:25
     |
1011 |         offset64: libc::off64_t = 0,
     |                         ^^^^^^^ help: a type alias with a similar name exists: `off_t`
     |
    ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
     |
1    | pub type off_t = i64;
     | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
    --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:1040:39
     |
1040 |         self.offset64(offset as libc::off64_t)
     |                                       ^^^^^^^ help: a type alias with a similar name exists: `off_t`
     |
    ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
     |
1    | pub type off_t = i64;
     | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
    --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:1051:25
     |
1051 |         offset64: libc::off64_t = 0,
     |                         ^^^^^^^ help: a type alias with a similar name exists: `off_t`
     |
    ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
     |
1    | pub type off_t = i64;
     | -------------- similarly named type alias `off_t` defined here

error[E0412]: cannot find type `off64_t` in crate `libc`
    --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:1072:39
     |
1072 |         self.offset64(offset as libc::off64_t)
     |                                       ^^^^^^^ help: a type alias with a similar name exists: `off_t`
     |
    ::: /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:1:1
     |
1    | pub type off_t = i64;
     | -------------- similarly named type alias `off_t` defined here

error[E0425]: cannot find value `SYS_io_uring_register` in crate `libc`
  --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/sys/mod.rs:45:40
   |
45 | const SYSCALL_REGISTER: c_long = libc::SYS_io_uring_register;
   |                                        ^^^^^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `SYS_io_uring_setup` in crate `libc`
  --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/sys/mod.rs:51:37
   |
51 | const SYSCALL_SETUP: c_long = libc::SYS_io_uring_setup;
   |                                     ^^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `SYS_io_uring_enter` in crate `libc`
  --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/sys/mod.rs:57:37
   |
57 | const SYSCALL_ENTER: c_long = libc::SYS_io_uring_enter;
   |                                     ^^^^^^^^^^^^^^^^^^ not found in `libc`

libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
error[E0308]: mismatched types
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:841:19
    |
841 |         sqe.len = mode;
    |         -------   ^^^^ expected `u32`, found `u16`
    |         |
    |         expected due to the type of this binding

libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
error[E0308]: mismatched types
    --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/opcode.rs:1469:19
     |
1469 |         sqe.len = mode;
     |         -------   ^^^^ expected `u32`, found `u16`
     |         |
     |         expected due to the type of this binding

libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
error[E0308]: mismatched types
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/sys/mod.rs:67:9
    |
66  |     to_result(syscall(
    |               ------- arguments to this function are incorrect
67  |         SYSCALL_REGISTER,
    |         ^^^^^^^^^^^^^^^^ expected `i32`, found `i64`
    |
note: function defined here
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:635:12
    |
635 |     pub fn syscall(num: ::c_int, ...) -> ::c_int;
    |            ^^^^^^^
help: you can convert an `i64` to an `i32` and panic if the converted value doesn't fit
    |
67  |         SYSCALL_REGISTER.try_into().unwrap(),
    |                         ++++++++++++++++++++

libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
error[E0308]: mismatched types
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/sys/mod.rs:93:23
    |
93  |     to_result(syscall(SYSCALL_SETUP, entries as c_long, p as c_long) as _)
    |               ------- ^^^^^^^^^^^^^ expected `i32`, found `i64`
    |               |
    |               arguments to this function are incorrect
    |
note: function defined here
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:635:12
    |
635 |     pub fn syscall(num: ::c_int, ...) -> ::c_int;
    |            ^^^^^^^
help: you can convert an `i64` to an `i32` and panic if the converted value doesn't fit
    |
93  |     to_result(syscall(SYSCALL_SETUP.try_into().unwrap(), entries as c_long, p as c_long) as _)
    |                                    ++++++++++++++++++++

libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
error[E0308]: mismatched types
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/sys/mod.rs:111:9
    |
110 |     to_result(syscall(
    |               ------- arguments to this function are incorrect
111 |         SYSCALL_ENTER,
    |         ^^^^^^^^^^^^^ expected `i32`, found `i64`
    |
note: function defined here
   --> /Users/xvilka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/src/unix/bsd/mod.rs:635:12
    |
635 |     pub fn syscall(num: ::c_int, ...) -> ::c_int;
    |            ^^^^^^^
help: you can convert an `i64` to an `i32` and panic if the converted value doesn't fit
    |
111 |         SYSCALL_ENTER.try_into().unwrap(),
    |                      ++++++++++++++++++++

Some errors have detailed explanations: E0308, E0412, E0425.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `io-uring` (lib) due to 30 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by ming1** [comment]
Hello XVilka,

Looks you miss libc-dev header file.

I verified qcow2-rs on both debian/ubuntu & fedora/rhel, but  don't get chance to play it on macOS.

And the built-in test code actually depends on io-uring which
should be  available only on linux, but it is likely to make the library work on mac or even windows. And it still need some time.

Anyway, thanks for the test.

Thanks,

**Comment by ming1** [comment]
Turns out it is caused by io-uring crate.

Now it becomes optional only on linux.

And the issue is solved in main.

**Comment by XVilka** [comment]
Thanks!
One more left:
```
error[E0425]: cannot find value `O_DIRECT` in crate `libc`
  --> src/sync_io.rs:28:68
   |
28 |                 libc::fcntl(file.as_raw_fd(), libc::F_SETFL, libc::O_DIRECT);
   |                                                                    ^^^^^^^^ not found in `libc`

libunwind: malformed __unwind_info at 0x183053CA8 bad second level page
For more information about this error, try `rustc --explain E0425`.
error: could not compile `qcow2-rs` (lib) due to previous error
```

**Comment by ming1** [comment]
Sorry, I don't have macos environment, and only test it in freebsd.

Can you test the fix in PR#2?

https://github.com/ublk-org/qcow2-rs/pull/2

**Comment by XVilka** [comment]
Solved by https://github.com/ublk-org/qcow2-rs/commit/0b4ef5295af0317b08d91c2207c02d1fe3627167
